name: CFML Testing Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    name: Test on ${{ matrix.cfml_engine }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cfml_engine: [lucee@4, lucee@5, adobe@2016, adobe@2018]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CFML TestBox Action
        uses: coldfumonkeh/cfml-testbox-action@v1
        with:
          cfml-engine: ${{ matrix.cfml_engine }}
